Iis fresh install/5.7
cinchy-co/Documentation pull request #120
Opened 2023-10-18 19:27 UTC by colinnashcinchy

Please include a summary of the change and issue. Please also include relevant motivation and context. List any required dependencies for this change.

Fixes IIS Fresh install

## Type

- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Release notes
- [x] Doc update

# Versions/Backporting

Please describe the applicable versions for the change.

**Doc version**:

# Testing 

Describe any testing, if applicable.
# Checklist:

- [ ] My code follows the style guidelines of this project.
- [ ] I have done an initial review.
- [ ] I have completed an assessment of possible topic pages affected by the change.
- [ ] My changes generate no new warnings
- [ ] (Optional) I have validated any automated changes.
- [ ] (If applicable) I have cherry picked changes and made a PR for other documentation versions

# Notes

Removed duplicate pages from an earlier TOC cleanup (rename from deployment-installation to just deployment)

2023-10-18 19:29 UTC, colinnashcinchy commented on deployment-guide/deployment-guides/iis-deployment-installation.md
Page that was changed to meet revised instructions.

2023-10-19 14:39 UTC, MKcinchy commented on deployment-guide/deployment-guides/iis-deployment-installation.md
> +1. Download and unzip the **"Cinchy vX.X"** application package from the
ensure consistency. We specified that it should be "Cinchy vX.X." to match the previous reference of "v5.6.2."

2023-10-19 14:43 UTC, MKcinchy commented on deployment-guide/deployment-guides/iis-deployment-installation.md
> +| `CinchyUri`                 | The base URL appended with `/Cinchy`.                                             | `http://localhost/Cinchy`              |
Add generic along with localhost : i.e <baseURL>/CinchySSO

2023-10-19 15:04 UTC, MKcinchy requested changes

2023-10-19 15:04 UTC, MKcinchy commented on deployment-guide/deployment-guides/iis-deployment-installation.md
> +| `CinchyUri`                 | The base URL appended with `/Cinchy`.                                             | `http://localhost/Cinchy`              |
Add generic base URL along with localhost : i.e {base_cinchy_url}/Cinchy

2023-10-19 15:04 UTC, MKcinchy commented on deployment-guide/deployment-guides/iis-deployment-installation.md
> +| `StsPublicOriginUri`        | Base URL of the `.well-known` discovery.                                          | `http://localhost/CinchySSO`           |
Add generic base URL along with localhost : i.e {base_cinchy_url}/CinchySSO

2023-10-19 15:04 UTC, MKcinchy commented on deployment-guide/deployment-guides/iis-deployment-installation.md
> +| `StsPrivateOriginUri`       | Private Base URL of the `.well-known` discovery.                                  | `http://localhost/CinchySSO`           |
Add generic base URL along with localhost : i.e {base_cinchy_url}/CinchySSO

2023-10-19 15:04 UTC, MKcinchy commented on deployment-guide/deployment-guides/iis-deployment-installation.md
> +1. Download and unzip the **"Cinchy vX.X"** application package from the
Ensure consistency of Cinchy version name; above we mentioned v.5.6.2

2023-10-19 15:04 UTC, MKcinchy commented on deployment-guide/deployment-guides/iis-deployment-installation.md
> +| `StsPrivateAuthorityUri` | Match your private Cinchy SSO URL. i.e                                              | `http://localhost/CinchySSO`          |
Add generic base URL along with localhost : i.e {base_cinchy_url}/CinchySSO

2023-10-19 15:04 UTC, MKcinchy commented on deployment-guide/deployment-guides/iis-deployment-installation.md
> +| `StsPublicAuthorityUri`  | Match your public Cinchy SSO URL. i.e                                               | `http://localhost/CinchySSO`          |
Add generic base URL along with localhost : i.e {base_cinchy_url}/CinchySSO

2023-10-19 15:04 UTC, MKcinchy commented on deployment-guide/deployment-guides/iis-deployment-installation.md
> +| `CinchyPrivateUri`       | Match your private Cinchy URL. i.e                                                  | `http://localhost/Cinchy`             |
Add generic base URL along with localhost : i.e {base_cinchy_url}/Cinchy

2023-10-19 15:04 UTC, MKcinchy commented on deployment-guide/deployment-guides/iis-deployment-installation.md
> +| `CinchyPublicUri`        | Match your public Cinchy URL.                                                       | `http://localhost/Cinchy`             |
Add generic base URL along with localhost : i.e {base_cinchy_url}/Cinchy

2023-10-19 15:04 UTC, MKcinchy commented on deployment-guide/deployment-guides/iis-deployment-installation.md
> +- [Cinchy V5.6.2.zip](#)
This is for version 5.6.2, if you're also updating version 5.7, please ensure the change is made to "v5.7" in the documentation.

2023-10-19 15:04 UTC, MKcinchy commented on deployment-guide/deployment-guides/iis-deployment-installation.md
> +Please note that the link to "Cinchy V5.6.2.zip" should be replaced with the
This is for version 5.6.2, if you're also updating version 5.7, please ensure the change is made to "v5.7" in the documentation.

2023-10-19 17:12 UTC, colinnashcinchy commented on deployment-guide/deployment-guides/iis-deployment-installation.md
> +- [Cinchy V5.6.2.zip](#)
Made it generic

2023-10-19 17:12 UTC, colinnashcinchy commented on deployment-guide/deployment-guides/iis-deployment-installation.md
> +Please note that the link to "Cinchy V5.6.2.zip" should be replaced with the
Removed section to reduce noise.

2023-10-24 18:46 UTC, MKcinchy approved these changes

2023-10-24 18:49 UTC, MKcinchy commented
reviewed the changes

2023-10-24 18:52 UTC, merged